apiVersion: v1
kind: Namespace
metadata:
  name: afixo-staging
  labels:
    app.kubernetes.io/part-of: afixo
    afixo.io/environment: staging
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
